# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

google-ID: ''

menu:
- {name: 'About', folder: 'pages', file: 'about.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'facebook', link: 'https://facebook.com/analisetransacionalSC/'}
- {icon: 'instagram', link: 'https://instagram.com/analisetransacional'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/company/analise-transacional.com'}

# Customize site text
pagination:
  next_page: 'Mais recente'
  previous_page: 'Mais antigo'

sharing_button_prompt: 'Compartilhe!'

related_posts: 'Você pode se interessar também...'

post_date_prefix: ''
