# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'analisetransacional'

google-ID: ''

bitrix-ID: '25493306'

CALENDAR_ID: 'analisetransacional.com_p8v1c0bj0hgtcgoec8hh2jj64c@group.calendar.google.com'
# CALENDAR_ID: '5g14sen28q58ujshh0fahtfl6k@group.calendar.google.com'

API_KEY: 'AIzaSyDe-QugIfWUllH1Z_43AroZhFJs7ERWKzI'

menu:
- {name: 'Artigos', folder: 'pages', file: 'artigos.html'}
- {name: 'Conteúdos', folder: 'pages', file: 'conteudos.html'}
- {name: 'Produtos', folder: 'pages', file: 'produtos.html'}
- {name: 'Mídia', folder: 'pages', file: 'midia.html'}
- {name: 'Sobre', folder: 'pages', file: 'sobre.html'}
- {name: 'Contato', folder: 'pages', file: 'contato.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'linkedin', link: 'https://www.linkedin.com/company/analise-transacional.com'}
- {icon: 'facebook', link: 'https://facebook.com/analisetransacionalSC/'}
- {icon: 'instagram', link: 'https://instagram.com/analisetransacional'}

# Customize site text
pagination:
  next_page: '>'
  previous_page: '<'

sharing_button_prompt: 'Compartilhe!'

related_posts: 'Artigos relacionados...'

post_date_prefix: ''
