---
label: Produto
hide_body: false
is_partial: false
fields:
- type: text
  label: layout
  name: layout
  default: product
  config:
    required: true
  hidden: true
- type: text
  name: title
  label: Título
  config:
    required: true
- type: text
  name: categories
  label: Categorias
  config:
    required: true
  default: produto
  hidden: true
- type: tag_list
  name: tags
  label: Tags
